site_name: Subcortex visualization

theme:
  name: material  
  logo: images/logo.png  # adjust the path as needed
  favicon: images/logo.ico
  palette:
    scheme: default
    primary: purple  # ← change this to your desired color
    accent: amber   # ← optional: affects buttons/links

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - md_in_html
  - attr_list

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: tutorial.ipynb
  - Atlas information: atlas_info.md
  - Using a custom atlas: custom_segmentation.md
  - Acknowledgments: acknowledgments.md
  - Cite this package: citation.md